name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: actions/setup-python@master
    - name: Install Firefox and xvfb
      run: |
        echo Installing firefox and xvfb
        sudo apt install firefox xvfb
        
    - name: Check installation results
      run: |
        python  --version
        node --version
        yarn --version
        xvfb-run --help
        firefox --version
