name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create tag
      run: |
        git tag "ACT-$(date +%d%m%Y-%H%M%S)"
        
    - name: push tag
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        tags: true
