name: deploy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: prepare envars
        run: |
          git fetch
          echo "REVISION=$(git describe --tags)" >> $GITHUB_ENV
      
      - name: update revision label
        run: |
          mkdir build
          echo "REVISI-${{ env.REVISION }}" > build/index.html

      - name: push ghpage
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
